##########gitlist###########
- hosts: gitlist-servers
  become: yes
  roles:
  - role: gitlist_server


###########etckeeper#########
- hosts: etckeeper-servers

- hosts: etckeeper-clients
  become: yes
  pre_tasks:
    - import_tasks: tasks/generate_key.yml
      when: uninstall_etckeeper == false

- hosts: etckeeper-servers
  become: yes
  roles:
  - role: etckeeper_server

- hosts: etckeeper-clients
  become: yes
  roles:
  - role: etckeeper_client

