- name: Create system accounts
  user:
    name: git-{{ hostvars[item]['ansible_hostname'] }}
    home: /home/git-{{ hostvars[item]['ansible_hostname'] }}
    state: present
  with_items: "{{ groups['etckeeper-clients'] }}"

- name: Creates directory
  file: path=/home/git-{{ hostvars[item]['ansible_hostname'] }}/.ssh/ state=directory
  with_items: "{{ groups['etckeeper-clients'] }}"

- name: chown directory
  file:
    path: /home/git-{{ hostvars[item]['ansible_hostname'] }}/repositories/{{ hostvars[item]['ansible_hostname'] }}.git
    state: directory
    owner: git-{{ hostvars[item]['ansible_hostname'] }}
    group: apache
    recurse: yes
  with_items: "{{ groups['etckeeper-clients'] }}"

- name: gitinit
  shell: git init --bare /home/git-{{ hostvars[item]['ansible_hostname'] }}/repositories/{{ hostvars[item]['ansible_hostname'] }}.git
  with_items: "{{ groups['etckeeper-clients'] }}"

- name: create repo
  file:
    path: /home/git-{{ hostvars[item]['ansible_hostname'] }}/repositories/{{ hostvars[item]['ansible_hostname'] }}.git
    owner: git-{{ hostvars[item]['ansible_hostname'] }}
    group: apache
    state: directory
    recurse: yes
  with_items: "{{ groups['etckeeper-clients'] }}"

- name: chown repo
  file:
    path: /home/git-{{ hostvars[item]['ansible_hostname'] }}/
    owner: git-{{ hostvars[item]['ansible_hostname'] }}
    group: apache
    mode: 0750
  with_items: "{{ groups['etckeeper-clients'] }}"


#############ssh#############

- name: create ssh folder
  file:
    path: /home/git-{{ hostvars[item]['ansible_hostname'] }}/.ssh/
    owner: git-{{ hostvars[item]['ansible_hostname'] }}
    group: apache
    state: directory
    recurse: yes
  with_items: "{{ groups['etckeeper-clients'] }}"